plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Protobuf runtime
    implementation 'com.google.protobuf:protobuf-java:3.25.3'

    // Logging
    implementation 'org.apache.logging.log4j:log4j-core:2.25.2'

    // Teste
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.3"
    }
}
