plugins {
  id 'java'
  id 'org.openjfx.javafxplugin' version '0.0.13'
  id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}
javafx {
  version = "20"
  modules = [ 'javafx.controls', 'javafx.fxml' ]
}


dependencies {
  testImplementation platform('org.junit:junit-bom:5.10.0')
  testImplementation 'org.junit.jupiter:junit-jupiter'
  implementation project(":Model")
  implementation project(":Networking")
  implementation project(":Services")
  implementation("org.apache.logging.log4j:log4j-core:2.24.3")
// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
  implementation("org.apache.logging.log4j:log4j-api:2.24.3")
  // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
}

test {
  useJUnitPlatform()
}
application{
  mainClass='org.example.client.StartClientRPC'
}