plugins {
    id 'java'
    id "me.champeau.jmh" version "0.7.1"
}

group = 'com.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17) // Adjust if using a different JDK
    }
}

repositories {
    mavenCentral()
    maven { url "https://jcenter.bintray.com/" } // Required for some older JMH versions
}

dependencies {
    // JUnit for normal tests
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

// https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-core
    testImplementation("org.openjdk.jmh:jmh-core:1.37")
// https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-generator-annprocess
    testImplementation("org.openjdk.jmh:jmh-generator-annprocess:1.37")
    // https://mvnrepository.com/artifact/it.unimi.dsi/fastutil
    implementation("it.unimi.dsi:fastutil:8.5.18")
    // https://mvnrepository.com/artifact/org.eclipse.collections/eclipse-collections
    implementation("org.eclipse.collections:eclipse-collections:13.0.0")
    // https://mvnrepository.com/artifact/com.koloboke/koloboke-api-jdk8
    implementation("com.koloboke:koloboke-api-jdk8:1.0.0")
    // https://mvnrepository.com/artifact/com.koloboke/koloboke-impl-jdk8
    implementation("com.koloboke:koloboke-impl-jdk8:1.0.0")
}

test {
    useJUnitPlatform()
}

jmh {
    warmupIterations = 2
    iterations = 2
    fork = 1
    threads = 1
    timeUnit = 'ns'
}
